=== adhitya97/Service-Oriented-Computing/LabExam1/Question 1/Company.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2016 (x64) (http://www.altova.com) by BITS-PILANI University, Dubai Campus (BITS-PILANI University, Dubai Campus) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="Company">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="Employee">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="FirstName" type="xs:string"/>
							<xs:element name="LastName" type="xs:string"/>
							<xs:element name="ContactNumber">
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:totalDigits value="5"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Email">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[a-zA-Z]{5}@gmail.com"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Address">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="City">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="Madurai"/>
													<xs:enumeration value="Hyderabad"/>
													<xs:enumeration value="Chennai"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="State">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="Andhra"/>
													<xs:enumeration value="Tamilnadu"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Zip">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="[0-9]{5}-[0-9]{4}"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="ID">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="[0-9]{2}-[A-Za-z]{3}"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== adhitya97/Service-Oriented-Computing/LabExam1/Question 1/CompanyDetails.xml
<?xml version="1.0" encoding="UTF-8"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/Admin/Desktop/2014A7PS0035U/Company.xsd">
	<Employee ID="12-AAZ">
		<FirstName>FirstName1</FirstName>
		<LastName>LastName1</LastName>
		<ContactNumber>11111</ContactNumber>
		<Email>asdqq@gmail.com</Email>
		<Address>
			<City>Madurai</City>
			<State>Tamilnadu</State>
			<Zip>11111-1111</Zip>
		</Address>
	</Employee>
	<Employee>
		<FirstName>FirstName2</FirstName>
		<LastName>LastName2</LastName>
		<ContactNumber>33333</ContactNumber>
		<Email>vbnma@gmail.com</Email>
		<Address>
			<City>Hyderabad</City>
			<State>Andhra</State>
			<Zip>22222-2222</Zip>
		</Address>
	</Employee>
</Company>
